-- Tabela para armazenar as equipes
CREATE TABLE teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Tabela para armazenar os jogadores, com referência à sua equipe
CREATE TABLE players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT REFERENCES teams(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    steam_link TEXT NOT NULL,
    discord TEXT NOT NULL,
    is_leader BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Tabela para estruturar as partidas da chave (bracket)
CREATE TABLE matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    round_number INT NOT NULL, -- 1: Quartas, 2: Semis, 3: Final
    match_in_round INT NOT NULL, -- Posição da partida na rodada
    team1_id BIGINT REFERENCES teams(id) ON DELETE SET NULL,
    team2_id BIGINT REFERENCES teams(id) ON DELETE SET NULL,
    winner_id BIGINT REFERENCES teams(id) ON DELETE SET NULL,
    next_match_id BIGINT REFERENCES matches(id) ON DELETE SET NULL, -- Aponta para a próxima partida na chave
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    CONSTRAINT unique_round_match UNIQUE (round_number, match_in_round)
);

-- Tabela para gerenciar as sessões de veto de mapas
-- Substitua a tabela vetos existente por esta
CREATE TABLE vetos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT REFERENCES matches(id) ON DELETE CASCADE NOT NULL,
    access_token UUID DEFAULT uuid_generate_v4() NOT NULL UNIQUE,
    format TEXT NOT NULL, -- 'MD1' ou 'MD3'
    status TEXT DEFAULT 'pending' NOT NULL, -- pending, in_progress, completed
    banned_maps JSONB NOT NULL DEFAULT '[]'::jsonb, -- Alterado para JSONB com valor padrão
    picked_maps JSONB NOT NULL DEFAULT '[]'::jsonb, -- Alterado para JSONB com valor padrão
    current_turn_team_id BIGINT REFERENCES teams(id),
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Permite acesso anônimo para leitura nas tabelas públicas
-- ATENÇÃO: Ajuste as políticas (policies) no painel do Supabase para um controle mais fino de segurança.
-- Por enquanto, isso facilita o desenvolvimento.
ALTER TABLE teams ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public teams are viewable by everyone." ON teams FOR SELECT USING (true);

ALTER TABLE players ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public players are viewable by everyone." ON players FOR SELECT USING (true);

ALTER TABLE matches ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public matches are viewable by everyone." ON matches FOR SELECT USING (true);

ALTER TABLE vetos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public vetos are viewable by everyone." ON vetos FOR SELECT USING (true);